name: Go

on:
  push:
    branches:
      - main
      - "release-**"
  pull_request:
    branches:
      - main
      - "release-**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Vendor
        run: go mod vendor

      - name: Test
        run: go test -v -mod vendor -race -timeout=2m
